### ISSUE TITLE
Order of operation

### ISSUE THREAD

**Issue by hyorkim11** [empatica/empalink-sample-project-android#1]
In the main activity, there are functions that aren't explicitly called.
Are they all being used implicitly? if so, what are some of the functions that are called?
There seems to be a lack of explanation about how to go about using this template as a basis.

Thanks!

**Comment by faustoempatica** [comment]
Hello @hyorkim11 

Please check the documentation from developers.empatica.com 

If you still have any doubts or issues, please write to support@empatica.com and we will be happy to help you out. 

Thanks
