### ISSUE TITLE
App cannot find devices

### ISSUE THREAD

**Issue by eadward** [empatica/empalink-sample-project-android#11]
Dear Team,

I create the APK for this project and installed it on my phone. I am using the latest version of the sample project and the Android SDK 2.1. 

Unfortunately, the app cannot find the device (it stays in state "READY - Turn on your device"), although I have the device registered in the developers area and I use the correct API key in the app code. 

Why would the app not detect and connect to the device? 

thanks!

Eduardo.

**Comment by A00107408** [comment]
Dear Team,

I create the APK for this project and installed it on my phone. I am using the latest version of the sample project and the Android SDK 2.1.

Unfortunately, the app cannot find the device (it stays in state "READY - Turn on your device"), although I have the device registered in the developers area and I use the correct API key in the app code.

Why would the app not detect and connect to the device?

thanks!

Eoghan

**Comment by raviteja-bhupatiraju** [comment]
@eadward @A00107408
Were you able to go forward from this? I have the same issue.

**Comment by EoghanHynes** [comment]
no

**Comment by eadward** [comment]
Can the Empatica team reply? We paid for a very expensive piece of equipment expecting that this would be a feature and it does not work. It has been years without an answer. Appalling!

**Comment by EoghanHynes** [comment]
> 
> 
> @eadward @A00107408
> Were you able to go forward from this? I have the same issue.

In the end I used the code from this repo to connect to the empatica.

https://github.com/debapratimsaha/EmpaticaUnityBLEClient

The code is in C# for Unity 3D, but C# is similar to Java, so maybe you can translate the code for use with Android. Just remove all of the Unity UI stuff and translate the socket code

**Comment by raviteja-bhupatiraju** [comment]
> > @eadward @A00107408
> > Were you able to go forward from this? I have the same issue.
> 
> In the end I used the code from this repo to connect to the empatica.
> 
> https://github.com/debapratimsaha/EmpaticaUnityBLEClient
> 
> The code is in C# for Unity 3D, but C# is similar to Java, so maybe you can translate the code for use with Android. Just remove all of the Unity dependencies and translate the TCP and socket code to java... should be very similar code.... and it connects fine to Empatica server for real time physiological data acquisition.

Thank you. We need to work without the Windows BLE server. Our subjects will wander out of range of the Windows box.
