### ISSUE TITLE
Device self-disconnect after some time

### ISSUE THREAD

**Issue by assaf007** [empatica/empalink-sample-project-android#15]
Hello,

I have the same problem as @qiriro (https://github.com/empatica/empalink-sample-project-android/issues/13).
My Empatica device keeps self-disconnecting at about 10 minutes of usage. I was wondering if there is any method in the Empatica android API that can allow me to know why this is happening? (the app does not throw any exception or anything that I can log).

Does anyone know why? what's the solution for this malfunction?

**Comment by assaf-hes** [comment]
I try the 2.2 released version, the sample app provided by Empatica cannot at all connect to the wrist. Is this a stable version or still under development?

Does someone know why the sample app is self disconnected from the E4 at about some minutes (about 10 minutes, sometimes more)? I set the streaming variable time like this: STREAMING_TIME = 1000000000, what's going wrong?
