### ISSUE TITLE
Missing IBI values

### ISSUE THREAD

**Issue by ChrizH** [empatica/empalink-sample-project-android#2]
Hello,

I have problems retrieving the IBI value from the connected E4, because the `didReceiveIBI()` method is almost never called by the `empalink-2.0 API` (delays >5s..10s).
The API delivers all other values perfectly with constant sampling rates for: BVP@64Hz, Accelerometer@32Hz, TMP&EDA@4Hz.
 
Is the IBI peak detector from the API wrong implemented?
Any idea how to solve this issue? I think I need to implement an own peak detector..

Regards,
Chriz

**Comment by faustoempatica** [comment]
The question was replied via our support center: support@empatica.com
