### ISSUE TITLE
Can't connect with my E4

### ISSUE THREAD

**Issue by yliu224** [empatica/empalink-sample-project-android#6]
My E4 works fine with the official app,Empatica RT,however,when I tried to run my application,E4 can't connect to the android device.The API_KEY is correct,and the my application will stop after executing the startScanning() method.Nothing will happen after executing the startScanning() method.Please help.Thanks.

**Comment by pregno** [comment]
Hi @yliu224, which version of Android are you using?

**Comment by yliu224** [comment]
I am using Android 6.0.1,and the device is Nexus 7.Should the EmpaStatus change into DISCOVERING after we call the startScanning ()?

**Comment by pregno** [comment]
ok, try the latest commit after the PR merge.
Starting from android 6.0 the location services are required for BLE scan, so probably this is the issue

(ref: [BluetoothLeScanner.startScan](https://developer.android.com/reference/android/bluetooth/le/BluetoothLeScanner.html#startScan(android.bluetooth.le.ScanCallback)))

**Comment by pregno** [comment]
We have published an update for the empalink (the new version is the 2.1) and an update for the sample project.
Let me know if you still have this issue.

**Comment by yliu224** [comment]
It works fine now!Thanks!
