### ISSUE TITLE
Sample project crashes on launch

### ISSUE THREAD

**Issue by amusse** [empatica/empalink-sample-project-android#7]
I am trying to run the sample project on Android 5.0.1 using Android Studio 2.2.3. I was previously able to get the sample project running perfectly fine until recently. Now, after launching the sample application I keep getting the following error. I rebuilt the project using the source from this repo and made no changes but only changed the API key, yet I still get this error:
`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.empatica.empalinksample, PID: 22605
                  com.empatica.empalink.ConfigurationProfileException: Login failed and you don't have a valid local configuration profile
                      at com.empatica.empalink.EmpaDeviceManager.b(EmpaDeviceManager.java:846)
                      at com.empatica.empalink.EmpaDeviceManager.a(EmpaDeviceManager.java:78)
                      at com.empatica.empalink.EmpaDeviceManager$b.a(EmpaDeviceManager.java:1016)
                      at com.empatica.empalink.EmpaDeviceManager$b.onPostExecute(EmpaDeviceManager.java:989)
                      at android.os.AsyncTask.finish(AsyncTask.java:632)
                      at android.os.AsyncTask.access$600(AsyncTask.java:177)
                      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:145)
                      at android.app.ActivityThread.main(ActivityThread.java:5951)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)`

Any idea on how to fix this? I tried my best to poke around the decompiled .class files to find the issue but didn't have any luck. Only thing I could do was confirm that my API key is valid by sending a post request to `https://www.empatica.com/connect/empalink/api_login.php` with my `api_key` and `api_version: 2.0` and got back an `ok` response.

**Comment by amusse** [comment]
Also, I am having issues with the iOS sample project too (http://developer.empatica.com/ios-sdk-tutorial-072.html) where it also crashes after trying to pair with my Empatica E4 device. I couldn't find the github repo for the iOS sample project, so if someone could direct me to where I should send my questions, that would be great.

**Comment by amusse** [comment]
Can I please get an update on this?

**Comment by pregno** [comment]
Seems the error generated when the API KEY is not valid.

BTW, we updated empalink and the sample project. Try to update them and let me know if you still have this issue.

**Comment by amusse** [comment]
Thanks for the reply. I will update them and try it as soon as I can. 

Can you also tell me where I can get support for the iOS sample project please? I've tried contacting customer support to get me in contact with the iOS dev, but it has been 2 months and I have yet to get a response. The iOS sample project also crashes when trying to pair with the Empatica E4 device (see attached log) using the 0.7.3 full SDK on an iPhone 6 using Xcode 8.1 and iOS 10.1.1. I have only changed the API key to a valid one in the sample project, as shown in the log.

LOG: [
![log](https://cloud.githubusercontent.com/assets/9970831/21933045/a9c0e4be-d971-11e6-90ab-d8f9ee05b0df.png)
](url)

**Comment by pregno** [comment]
For iOS I suggest you to update the SDK because seems to be an old bug already solved.

**Comment by pregno** [comment]
Seems to be an old bug already solved with the latest SDK. 
Are you using also the latest sample project?

**Comment by amusse** [comment]
I downloaded the iOS sample project from here: http://developer.empatica.com/ios-sdk-tutorial-072.html and clicked "Download the **single device** example Xcode project." which downloaded empatica-ios-sdk-sample-project-0.7.3-single-device.zip. Also downloaded it from here: https://github.com/empatica/empatica.github.io/blob/master/empatica-ios-sdk-sample-project-0.7.3-single-device.zip, but that also downloads the same zip file. When I run the project as is, I get the error I explained above. Though it seems the SDK for the _sample project_ wasn't updated. After replacing the SDK of the sample project with the most recent SDK version (which is "v0.7.3 full" from Sept. 16, 2015) from my Developers Area, it seems to work fine.

**Comment by pregno** [comment]
Perfect.
I'll wait a feedback on android before closing this issue.

**Comment by jkpolitz** [comment]
@pregno I am having the same iOS error. "API authentication FAIL! Reason: Connection Error and no valid local profile" I have tried to replace the SDK like amusse suggested but receive the same error. I have also been in communication with Mzia from the Empatica Help Center for over a month with no luck.

**Comment by samuelescobarg** [comment]
Greetings, is this issue solved? Im experiencing the same problem and  I've done what was mentioned in previous posts. I'm using Xcode 8 and Compiling for iOS10.3. When running I get an "Connection Error and no valid local profile" after calling authenticateWithAPIKey and this causes the expected "API key not set exception" message when trying to discover devices. I've changed API keys, changed programming languages (OC to Swift), and changed my internet connection due to an empatica@support suggestion.
What could be the reason of this issue?

I would really appreciate if you could help me.

Best regards
Samuel E

**Comment by snavjivan** [comment]
I am having the exact same issues as Samuel described above.

A solution would be most appreciated.

**Comment by samuelescobarg** [comment]
@snavjivan have you solved this issue? I've written to their support department and haven´t heard from them. If you managed to solve this please let me know.

Best Regards

**Comment by attilabalind** [comment]
I had the same problem and in my case the solution was that I needed to connect to the internet before I started the app. I hope it helps.

Best regards

**Comment by AminAminifar** [comment]
My problem also was resolved in the same way; when I connected my phone to the internet the app started working...

> I had the same problem and in my case the solution was that I needed to connect to the internet before I started the app. I hope it helps.
> 
> Best regards
