### ISSUE TITLE
Device disconnected before starting a session

### ISSUE THREAD

**Issue by eivindflobak** [empatica/empalink-sample-project-android#9]
Every other session or so I get this error. Is this a known issue? Also, would it be possible to get a callback when this warning is invoked? Would be nice to update the UI when this happens for usability. I cannot use `EmpaStatus.DISCONNECTED` because it is invoked too often and in some cases will be confusing for the user.

`04-10 12:47:29.611 10948-15146/com.empatica.empalinksample D/BluetoothGatt: onClientConnectionState() - status=22 clientIf=6 device=00:07:80:F2:17:76`
`04-10 12:47:29.611 10948-15146/com.empatica.empalinksample D/SensorService: Entered didUpdateStatus`
`04-10 12:47:29.612 10948-15146/com.empatica.empalinksample D/SensorService: Disconnected`
`04-10 12:47:29.612 10948-10948/com.empatica.empalinksample I/HomeFragment: disconnected`
`04-10 12:47:29.612 10948-15146/com.empatica.empalinksample W/EmpaDeviceManager: Device disconnected before starting a session`

`SensorService` and `HomeFragment` are LogCat outputs from my implementation that reflect EmpaStatus states.

**Comment by vadimmelnicuk** [comment]
I experience same issue quite often. Any input from devs on this?

**Comment by Dabin22** [comment]
I experience same issue. now @eivindflobak or @vadimmelnicuk Do you have solution?

**Comment by vadimmelnicuk** [comment]
@Dabin22 I contacted Empatica about a week ago however, haven't heard back yet.

**Comment by Dabin22** [comment]
@vadimmelnicuk There is no response to such a situation elsewhere. :(

**Comment by vadimmelnicuk** [comment]
@Dabin22 Well, the customer service picked the issue up and passed it onto tech team. Hopefully, they will come up with a fix.

**Comment by Tazrof** [comment]
I upvote this issue, this occur too many times.

**Comment by vadimmelnicuk** [comment]
@Tazrof Agree, it happens in about 1 in 4 connection attempts in my case. I am using the latest SDK.
